language: c

matrix:
  include:
    - os: osx
      addons:
        homebrew:
          packages:
            - ccache
            - meson
            - ninja
            - libmpdclient
            - check

cache:
  ccache: true
  directories:
    - $HOME/Library/Caches/Homebrew

before_cache:
  - test "$TRAVIS_OS_NAME" != "osx" || brew cleanup

before_install:
  - test "$TRAVIS_OS_NAME" != "osx" || export PATH="/usr/local/opt/ccache/libexec:$PATH"
  - test "$TRAVIS_OS_NAME" != "osx" || export HOMEBREW_NO_ANALYTICS=1

install:

before_script:
  - ccache -s

script:
  - OPTIONS="-Dtest=true"
  - meson . output $OPTIONS
  - ninja -v -C output test
  - ccache -s
